### ISSUE TITLE
Exception raised when trying to process gzipped data

### ISSUE THREAD

**Issue by harleyh** [EclecticIQ/cabby#37]
Hello,
I'm receiving gzip compressed data from a TAXII server. When cabby tries to process the data the following exception is raised:

> Traceback (most recent call last):
  File "test.py", line 14, in <module>
    discovery = ais_client.discover_services()
  File "/home/harley/Workspace/github/cabby/cabby/abstract.py", line 304, in discover_services
    response = self._discovery_request(uri)
  File "/home/harley/Workspace/github/cabby/cabby/client11.py", line 29, in _discovery_request
    response = self._execute_request(request, uri=uri)
  File "/home/harley/Workspace/github/cabby/cabby/abstract.py", line 202, in _execute_request
    taxii_binding=self.taxii_binding)
  File "/home/harley/Workspace/github/cabby/cabby/dispatcher.py", line 81, in send_taxii_request
    obj = next(gen)
  File "/home/harley/Workspace/github/cabby/cabby/dispatcher.py", line 170, in _parse_response
    action, root = next(gen)
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/lxml.etree.c:144543)
io.UnsupportedOperation: seek

I'm not sure exactly what the issue is but I was able to get around this by using StringIO with  response.content in dispatcher.py instead of attempting to manually decompress the raw content.

**Comment by traut** [comment]
@harleyh hm, I haven't seen this issue before - we tested Cabby with gzipped responses and it worked fine. I'll investigate.

using `response.content` in dispatcher helps because `requests` lib takes care of decompression. The drawback here is that this change makes useless stream parsing and leads to higher memory consumption.

**Comment by traut** [comment]
@harleyh could you please provide some details about your setup? OS, Python version, Cabby version

**Comment by harleyh** [comment]
@traut,
I thought there could be excessive memory usage by using response.content as well. Though, wouldn't the memory usage profile ultimately be the same in either case? My current setup is as follows:
Ubuntu 16.04 LTS
Python 2.7.12
Requests 2.11.1
Cabby 0.1.17a1

**Comment by traut** [comment]
@harleyh thanks! I'll try to reproduce

**Comment by traut** [comment]
fixed for python <v3.2 in 921d2925b9ecb92f36c78d6102084ebd0b79b071
