### ISSUE TITLE
Exception occurs When i use poll function 

### ISSUE THREAD

**Issue by xiaochao** [EclecticIQ/cabby#43]
content_blocks = client.poll(collection_name='collection-A', begin_date='2017-06-29T19:37:05+08:00', end_date='2017-06-29T20:37:05+08:00')

Traceback (most recent call last):
  File "poll.py", line 17, in <module>
    for block in content_blocks:
  File "/usr/lib/python2.7/site-packages/cabby/client11.py", line 485, in poll
    service_type=const.SVC_POLL)
  File "/usr/lib/python2.7/site-packages/cabby/abstract.py", line 205, in _execute_request
    timeout=self.timeout)
  File "/usr/lib/python2.7/site-packages/cabby/dispatcher.py", line 91, in send_taxii_request
    raise UnsuccessfulStatusError(obj)
cabby.exceptions.UnsuccessfulStatusError: FAILURE: There was a failure while executing the message handler

**Comment by traut** [comment]
hey @xiaochao, sorry for the late reply. This error does not say much -- it just says that server returned an error status response. I'll close this issue and make a note to make this exception better worded. 

as about your exception -- please check server's log to see what is wrong

**Comment by xiaochao** [comment]
Thanks for your reply,i check the log found a config item about https error.
