### ISSUE TITLE
ERROR: __init__() got an unexpected keyword argument 'recover'

### ISSUE THREAD

**Issue by zacharycheng** [EclecticIQ/cabby#53]
when I try to use cabby to upload a xml file to the taxii server, I always got the response :ERROR: __init__() got an unexpected keyword argument 'recover'
what can I do to solve this problem? Thanks

**Comment by zacharycheng** [comment]
this is not happening when I try to upload using private IP address in the internal network, only occurs when I try to upload using the public address from external network

**Comment by MojoJojo** [comment]
taxii-discovery --path https://otx.alienvault.com/taxii/discovery -v
2019-06-20 12:57:01,380 cabby.dispatcher INFO: Sending Discovery_Request to https://otx.alienvault.com/taxii/discovery
2019-06-20 12:57:01,380 cabby.dispatcher DEBUG: Request:
<taxii_11:Discovery_Request xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="33abcdbe-451e-4823-a66b-716b2fa45226"/>

2019-06-20 12:57:01,383 urllib3.connectionpool DEBUG: Starting new HTTPS connection (1): otx.alienvault.com:443
2019-06-20 12:57:02,707 urllib3.connectionpool DEBUG: https://otx.alienvault.com:443 "POST /taxii/discovery HTTP/1.1" 200 441


The example is copied/pasted from https://www.alienvault.com/blogs/security-essentials/otx-is-now-a-free-stix-taxii-server
2019-06-20 12:57:02,708 cabby.cli.commons ERROR: __init__() got an unexpected keyword argument 'recover'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cabby/cli/commons.py", line 171, in run_client
    run_func(client, args.uri, args)
  File "/usr/lib/python2.7/site-packages/cabby/cli/discovery.py", line 7, in _runner
    services = client.discover_services(uri=path)
  File "/usr/lib/python2.7/site-packages/cabby/abstract.py", line 292, in discover_services
    response = self._discovery_request(uri)
  File "/usr/lib/python2.7/site-packages/cabby/client11.py", line 27, in _discovery_request
    response = self._execute_request(request, uri=uri)
  File "/usr/lib/python2.7/site-packages/cabby/abstract.py", line 190, in _execute_request
    timeout=self.timeout)
  File "/usr/lib/python2.7/site-packages/cabby/dispatcher.py", line 57, in send_taxii_request
    obj = next(gen)
  File "/usr/lib/python2.7/site-packages/cabby/dispatcher.py", line 211, in _parse_response
    huge_tree=support_huge_trees)
  File "iterparse.pxi", line 368, in lxml.etree.iterparse.__init__ (src/lxml/lxml.etree.c:113193)
TypeError: __init__() got an unexpected keyword argument 'recover'

**Comment by traut** [comment]
this part is the root of the issue, @MojoJojo:
```
File "iterparse.pxi", line 368, in lxml.etree.iterparse.init (src/lxml/lxml.etree.c:113193)
TypeError: init() got an unexpected keyword argument 'recover'
```
`iterparse.__init__` supports `recover` argument ([see docs](https://lxml.de/api/lxml.etree.iterparse-class.html#__init__)).

make sure you use proper lxml version
