### ISSUE TITLE
recursive polling with fulfillment_client 

### ISSUE THREAD

**Issue by sriramvonline** [eclecticiq/cabby#79]
I have attached output of Taxii client below cabby client log.

**With fulfillment_client cabby is recursively polling with next result-part-number. and it never stops... 
result-part-number = 2 is not asking check result-part-number = 3 (can check the taxii client log)**
 
this is end of first block.
```
2021-01-20 12:02:18,025 cabby.dispatcher DEBUG: Stream element:
<taxii_11:Poll_Response xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#" collection_name="PhishTank" more="true" result_id="1582588800404:1582675200404" result_part_number="1" in_response_to="cb280ba7-3d4b-46e1-8568-de3f394d3086" message_id="urn:uuid:2c6a068a-983e-4de7-89e1-739aedaf9e93"><taxii_11:Exclusive_Begin_Timestamp>2020-02-25T00:00:00.404174Z</taxii_11:Exclusive_Begin_Timestamp><taxii_11:Inclusive_End_Timestamp>2020-02-26T00:00:00.404174Z</taxii_11:Inclusive_End_Timestamp><taxii_11:Record_Count partial_count="false">500</taxii_11:Record_Count></taxii_11:Poll_Response>
```

_Issue while downloading from 2 block, which is not a proper stix package, so cabbly client is downloading it again and again and waits for end of package_

```
2021-01-20 12:02:18,027 cabby.dispatcher INFO: Sending Poll_Fulfillment to https://partnerstage.threatconnect.com/api/taxii/poll/
2021-01-20 12:02:18,027 cabby.dispatcher DEBUG: Request:
<taxii_11:Poll_Fulfillment xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="5fdf99ad-471c-4ac6-8fd0-52d4c40498b9" collection_name="PhishTank" result_id="1582588800404:1582675200404" **result_part_number="2**"/>

2021-01-20 12:02:18,028 urllib3.connectionpool DEBUG: Starting new HTTPS connection (1): partnerstage.threatconnect.com
2021-01-20 12:02:22,034 urllib3.connectionpool DEBUG: https://partnerstage.threatconnect.com:443 "POST /api/taxii/poll/ HTTP/1.1" 200 662
2021-01-20 12:02:22,040 cabby.dispatcher DEBUG: Stream element:
<taxii_11:Content_Block xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#"><taxii_11:Content_Binding binding_id="urn:stix.mitre.org:xml:1.1.1"/><taxii_11:Content><stix:STIX_Package xmlns="http://xml/metadataSharing.xsd" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:threatconnect="http://threatconnect.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="threatconnect:STIXPackage-c10f04c3-cf4e-46d7-be66-1e3f7a78d64f" timestamp="2021-01-20T12:02:59.008Z" version="1.1.1" xsi:schemaLocation="http://stix.mitre.org/stix-1 http://stix.mitre.org/XMLSchema/core/1.1.1/stix_core.xsd"><stix:STIX_Header><stix:Title>Report: PhishTank</stix:Title><stix:Package_Intent>INDICATORS</stix:Package_Intent></stix:STIX_Header><stix:Indicators/></stix:STIX_Package></taxii_11:Content></taxii_11:Content_Block>
<stix:STIX_Package xmlns="http://xml/metadataSharing.xsd" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:threatconnect="http://threatconnect.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#" id="threatconnect:STIXPackage-c10f04c3-cf4e-46d7-be66-1e3f7a78d64f" timestamp="2021-01-20T12:02:59.008Z" version="1.1.1" xsi:schemaLocation="http://stix.mitre.org/stix-1 http://stix.mitre.org/XMLSchema/core/1.1.1/stix_core.xsd"><stix:STIX_Header><stix:Title>Report: PhishTank</stix:Title><stix:Package_Intent>INDICATORS</stix:Package_Intent></stix:STIX_Header><stix:Indicators/></stix:STIX_Package>
2021-01-20 12:02:22,044 cabby.dispatcher DEBUG: Stream element:
<taxii_11:Poll_Response xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#" collection_name="PhishTank" more="false" result_id="1582588800404:1582675200404" result_part_number="2" in_response_to="5fdf99ad-471c-4ac6-8fd0-52d4c40498b9" message_id="urn:uuid:1a657342-562a-404b-a201-d3b88bc6e17a"><taxii_11:Exclusive_Begin_Timestamp>2020-02-25T00:00:00.404Z</taxii_11:Exclusive_Begin_Timestamp><taxii_11:Inclusive_End_Timestamp>2020-02-26T00:00:00.404Z</taxii_11:Inclusive_End_Timestamp><taxii_11:Record_Count partial_count="false">508</taxii_11:Record_Count></taxii_11:Poll_Response>

```

```
2021-01-20 12:02:22,045 cabby.dispatcher INFO: Sending Poll_Fulfillment to https://partnerstage.threatconnect.com/api/taxii/poll/
2021-01-20 12:02:22,046 cabby.dispatcher DEBUG: Request:
<taxii_11:Poll_Fulfillment xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="28d56e45-b948-47d3-9b69-90887f29e3a0" collection_name="PhishTank" result_id="1582588800404:1582675200404" **result_part_number="3**"/>

2021-01-20 12:02:22,047 urllib3.connectionpool DEBUG: Starting new HTTPS connection (1): partnerstage.threatconnect.com
2021-01-20 12:02:26,097 urllib3.connectionpool DEBUG: https://partnerstage.threatconnect.com:443 "POST /api/taxii/poll/ HTTP/1.1" 200 662
2021-01-20 12:02:26,100 cabby.dispatcher DEBUG: Stream element:
<taxii_11:Content_Block xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#"><taxii_11:Content_Binding binding_id="urn:stix.mitre.org:xml:1.1.1"/><taxii_11:Content><stix:STIX_Package xmlns="http://xml/metadataSharing.xsd" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:threatconnect="http://threatconnect.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="threatconnect:STIXPackage-11cd8863-f3e5-415e-959e-db9f29263745" timestamp="2021-01-20T12:03:02.914Z" version="1.1.1" xsi:schemaLocation="http://stix.mitre.org/stix-1 http://stix.mitre.org/XMLSchema/core/1.1.1/stix_core.xsd"><stix:STIX_Header><stix:Title>Report: PhishTank</stix:Title><stix:Package_Intent>INDICATORS</stix:Package_Intent></stix:STIX_Header><stix:Indicators/></stix:STIX_Package></taxii_11:Content></taxii_11:Content_Block>
<stix:STIX_Package xmlns="http://xml/metadataSharing.xsd" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:threatconnect="http://threatconnect.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#" id="threatconnect:STIXPackage-11cd8863-f3e5-415e-959e-db9f29263745" timestamp="2021-01-20T12:03:02.914Z" version="1.1.1" xsi:schemaLocation="http://stix.mitre.org/stix-1 http://stix.mitre.org/XMLSchema/core/1.1.1/stix_core.xsd"><stix:STIX_Header><stix:Title>Report: PhishTank</stix:Title><stix:Package_Intent>INDICATORS</stix:Package_Intent></stix:STIX_Header><stix:Indicators/></stix:STIX_Package>
2021-01-20 12:02:26,102 cabby.dispatcher DEBUG: Stream element:
<taxii_11:Poll_Response xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#" collection_name="PhishTank" more="false" result_id="1582588800404:1582675200404" result_part_number="3" in_response_to="28d56e45-b948-47d3-9b69-90887f29e3a0" message_id="urn:uuid:5e0116f5-ddaa-4d98-aa63-41afa0e8ce0e"><taxii_11:Exclusive_Begin_Timestamp>2020-02-25T00:00:00.404Z</taxii_11:Exclusive_Begin_Timestamp><taxii_11:Inclusive_End_Timestamp>2020-02-26T00:00:00.404Z</taxii_11:Inclusive_End_Timestamp><taxii_11:Record_Count partial_count="false">508</taxii_11:Record_Count></taxii_11:Poll_Response>

```

```
2021-01-20 12:02:26,103 cabby.dispatcher INFO: Sending Poll_Fulfillment to https://partnerstage.threatconnect.com/api/taxii/poll/
2021-01-20 12:02:26,103 cabby.dispatcher DEBUG: Request:
<taxii_11:Poll_Fulfillment xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="699e0f1d-07b1-43de-a386-dfc91734f0ad" collection_name="PhishTank" result_id="1582588800404:1582675200404" **result_part_number="4"**/>

2021-01-20 12:02:26,105 urllib3.connectionpool DEBUG: Starting new HTTPS connection (1): partnerstage.threatconnect.com
2021-01-20 12:02:30,395 urllib3.connectionpool DEBUG: https://partnerstage.threatconnect.com:443 "POST /api/taxii/poll/ HTTP/1.1" 200 661
2021-01-20 12:02:30,399 cabby.dispatcher DEBUG: Stream element:
<taxii_11:Content_Block xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#"><taxii_11:Content_Binding binding_id="urn:stix.mitre.org:xml:1.1.1"/><taxii_11:Content><stix:STIX_Package xmlns="http://xml/metadataSharing.xsd" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:threatconnect="http://threatconnect.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="threatconnect:STIXPackage-3b545c81-bd47-44a9-acfa-98fa6d969074" timestamp="2021-01-20T12:03:06.873Z" version="1.1.1" xsi:schemaLocation="http://stix.mitre.org/stix-1 http://stix.mitre.org/XMLSchema/core/1.1.1/stix_core.xsd"><stix:STIX_Header><stix:Title>Report: PhishTank</stix:Title><stix:Package_Intent>INDICATORS</stix:Package_Intent></stix:STIX_Header><stix:Indicators/></stix:STIX_Package></taxii_11:Content></taxii_11:Content_Block>
<stix:STIX_Package xmlns="http://xml/metadataSharing.xsd" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:threatconnect="http://threatconnect.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#" id="threatconnect:STIXPackage-3b545c81-bd47-44a9-acfa-98fa6d969074" timestamp="2021-01-20T12:03:06.873Z" version="1.1.1" xsi:schemaLocation="http://stix.mitre.org/stix-1 http://stix.mitre.org/XMLSchema/core/1.1.1/stix_core.xsd"><stix:STIX_Header><stix:Title>Report: PhishTank</stix:Title><stix:Package_Intent>INDICATORS</stix:Package_Intent></stix:STIX_Header><stix:Indicators/></stix:STIX_Package>
2021-01-20 12:02:30,401 cabby.dispatcher DEBUG: Stream element:
<taxii_11:Poll_Response xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#" collection_name="PhishTank" more="false" result_id="1582588800404:1582675200404" result_part_number="4" in_response_to="699e0f1d-07b1-43de-a386-dfc91734f0ad" message_id="urn:uuid:10850dd7-d201-43c0-829d-5140bd54ce73"><taxii_11:Exclusive_Begin_Timestamp>2020-02-25T00:00:00.404Z</taxii_11:Exclusive_Begin_Timestamp><taxii_11:Inclusive_End_Timestamp>2020-02-26T00:00:00.404Z</taxii_11:Inclusive_End_Timestamp><taxii_11:Record_Count partial_count="false">508</taxii_11:Record_Count></taxii_11:Poll_Response>
```

```
2021-01-20 12:02:30,403 cabby.dispatcher INFO: Sending Poll_Fulfillment to https://partnerstage.threatconnect.com/api/taxii/poll/
2021-01-20 12:02:30,403 cabby.dispatcher DEBUG: Request:
<taxii_11:Poll_Fulfillment xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="e3938bd9-1f2c-4252-b6cd-3cb6232fc0ad" collection_name="PhishTank" result_id="1582588800404:1582675200404" **result_part_number="5**"/>

2021-01-20 12:02:30,405 urllib3.connectionpool DEBUG: Starting new HTTPS connection (1): partnerstage.threatconnect.com
2021-01-20 12:02:35,678 urllib3.connectionpool DEBUG: https://partnerstage.threatconnect.com:443 "POST /api/taxii/poll/ HTTP/1.1" 200 661
2021-01-20 12:02:35,682 cabby.dispatcher DEBUG: Stream element:
<taxii_11:Content_Block xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#"><taxii_11:Content_Binding binding_id="urn:stix.mitre.org:xml:1.1.1"/><taxii_11:Content><stix:STIX_Package xmlns="http://xml/metadataSharing.xsd" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:threatconnect="http://threatconnect.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="threatconnect:STIXPackage-9a530212-be91-4aa4-8560-d7525a2cf00f" timestamp="2021-01-20T12:03:12.631Z" version="1.1.1" xsi:schemaLocation="http://stix.mitre.org/stix-1 http://stix.mitre.org/XMLSchema/core/1.1.1/stix_core.xsd"><stix:STIX_Header><stix:Title>Report: PhishTank</stix:Title><stix:Package_Intent>INDICATORS</stix:Package_Intent></stix:STIX_Header><stix:Indicators/></stix:STIX_Package></taxii_11:Content></taxii_11:Content_Block>
<stix:STIX_Package xmlns="http://xml/metadataSharing.xsd" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:threatconnect="http://threatconnect.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#" id="threatconnect:STIXPackage-9a530212-be91-4aa4-8560-d7525a2cf00f" timestamp="2021-01-20T12:03:12.631Z" version="1.1.1" xsi:schemaLocation="http://stix.mitre.org/stix-1 http://stix.mitre.org/XMLSchema/core/1.1.1/stix_core.xsd"><stix:STIX_Header><stix:Title>Report: PhishTank</stix:Title><stix:Package_Intent>INDICATORS</stix:Package_Intent></stix:STIX_Header><stix:Indicators/></stix:STIX_Package>
2021-01-20 12:02:35,683 cabby.dispatcher DEBUG: Stream element:
<taxii_11:Poll_Response xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#" collection_name="PhishTank" more="false" result_id="1582588800404:1582675200404" result_part_number="5" in_response_to="e3938bd9-1f2c-4252-b6cd-3cb6232fc0ad" message_id="urn:uuid:48b06dec-fc0a-4c8b-8ad2-61570e3a9f97"><taxii_11:Exclusive_Begin_Timestamp>2020-02-25T00:00:00.404Z</taxii_11:Exclusive_Begin_Timestamp><taxii_11:Inclusive_End_Timestamp>2020-02-26T00:00:00.404Z</taxii_11:Inclusive_End_Timestamp><taxii_11:Record_Count partial_count="false">508</taxii_11:Record_Count></taxii_11:Poll_Response>
```

```
2021-01-20 12:02:35,685 cabby.dispatcher INFO: Sending Poll_Fulfillment to https://partnerstage.threatconnect.com/api/taxii/poll/
2021-01-20 12:02:35,685 cabby.dispatcher DEBUG: Request:
<taxii_11:Poll_Fulfillment xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="92353625-dcef-4629-99c6-f17a8b7a26ec" collection_name="PhishTank" result_id="1582588800404:1582675200404" **r****esult_part_number="6**"/>

2021-01-20 12:02:35,687 urllib3.connectionpool DEBUG: Starting new HTTPS connection (1): partnerstage.threatconnect.com
2021-01-20 12:02:41,216 urllib3.connectionpool DEBUG: https://partnerstage.threatconnect.com:443 "POST /api/taxii/poll/ HTTP/1.1" 200 662
2021-01-20 12:02:41,222 cabby.dispatcher DEBUG: Stream element:
<taxii_11:Content_Block xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#"><taxii_11:Content_Binding binding_id="urn:stix.mitre.org:xml:1.1.1"/><taxii_11:Content><stix:STIX_Package xmlns="http://xml/metadataSharing.xsd" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:threatconnect="http://threatconnect.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="threatconnect:STIXPackage-02f61192-d97a-4b7c-9326-22c57b65cde6" timestamp="2021-01-20T12:03:18.292Z" version="1.1.1" xsi:schemaLocation="http://stix.mitre.org/stix-1 http://stix.mitre.org/XMLSchema/core/1.1.1/stix_core.xsd"><stix:STIX_Header><stix:Title>Report: PhishTank</stix:Title><stix:Package_Intent>INDICATORS</stix:Package_Intent></stix:STIX_Header><stix:Indicators/></stix:STIX_Package></taxii_11:Content></taxii_11:Content_Block>
<stix:STIX_Package xmlns="http://xml/metadataSharing.xsd" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:threatconnect="http://threatconnect.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#" id="threatconnect:STIXPackage-02f61192-d97a-4b7c-9326-22c57b65cde6" timestamp="2021-01-20T12:03:18.292Z" version="1.1.1" xsi:schemaLocation="http://stix.mitre.org/stix-1 http://stix.mitre.org/XMLSchema/core/1.1.1/stix_core.xsd"><stix:STIX_Header><stix:Title>Report: PhishTank</stix:Title><stix:Package_Intent>INDICATORS</stix:Package_Intent></stix:STIX_Header><stix:Indicators/></stix:STIX_Package>
2021-01-20 12:02:41,225 cabby.dispatcher DEBUG: Stream element:
<taxii_11:Poll_Response xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#" collection_name="PhishTank" more="false" result_id="1582588800404:1582675200404" result_part_number="6" in_response_to="92353625-dcef-4629-99c6-f17a8b7a26ec" message_id="urn:uuid:19a4aaf6-72e6-4c73-a89b-4fb269113594"><taxii_11:Exclusive_Begin_Timestamp>2020-02-25T00:00:00.404Z</taxii_11:Exclusive_Begin_Timestamp><taxii_11:Inclusive_End_Timestamp>2020-02-26T00:00:00.404Z</taxii_11:Inclusive_End_Timestamp><taxii_11:Record_Count partial_count="false">508</taxii_11:Record_Count></taxii_11:Poll_Response>

```

```
2021-01-20 12:02:41,227 cabby.dispatcher INFO: Sending Poll_Fulfillment to https://partnerstage.threatconnect.com/api/taxii/poll/
2021-01-20 12:02:41,227 cabby.dispatcher DEBUG: Request:
<taxii_11:Poll_Fulfillment xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="2cb6ecfa-7647-4510-b513-17abc4753938" collection_name="PhishTank" result_id="1582588800404:1582675200404" r**esult_part_number="7"**/>

2021-01-20 12:02:41,229 urllib3.connectionpool DEBUG: Starting new HTTPS connection (1): partnerstage.threatconnect.com
2021-01-20 12:02:45,741 urllib3.connectionpool DEBUG: https://partnerstage.threatconnect.com:443 "POST /api/taxii/poll/ HTTP/1.1" 200 662
2021-01-20 12:02:45,748 cabby.dispatcher DEBUG: Stream element:
<taxii_11:Content_Block xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#"><taxii_11:Content_Binding binding_id="urn:stix.mitre.org:xml:1.1.1"/><taxii_11:Content><stix:STIX_Package xmlns="http://xml/metadataSharing.xsd" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:threatconnect="http://threatconnect.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="threatconnect:STIXPackage-adbee82f-f87e-4276-9ad4-93c1677353e3" timestamp="2021-01-20T12:03:20.561Z" version="1.1.1" xsi:schemaLocation="http://stix.mitre.org/stix-1 http://stix.mitre.org/XMLSchema/core/1.1.1/stix_core.xsd"><stix:STIX_Header><stix:Title>Report: PhishTank</stix:Title><stix:Package_Intent>INDICATORS</stix:Package_Intent></stix:STIX_Header><stix:Indicators/></stix:STIX_Package></taxii_11:Content></taxii_11:Content_Block>
<stix:STIX_Package xmlns="http://xml/metadataSharing.xsd" xmlns:stix="http://stix.mitre.org/stix-1" xmlns:threatconnect="http://threatconnect.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#" id="threatconnect:STIXPackage-adbee82f-f87e-4276-9ad4-93c1677353e3" timestamp="2021-01-20T12:03:20.561Z" version="1.1.1" xsi:schemaLocation="http://stix.mitre.org/stix-1 http://stix.mitre.org/XMLSchema/core/1.1.1/stix_core.xsd"><stix:STIX_Header><stix:Title>Report: PhishTank</stix:Title><stix:Package_Intent>INDICATORS</stix:Package_Intent></stix:STIX_Header><stix:Indicators/></stix:STIX_Package>
2021-01-20 12:02:45,749 cabby.dispatcher DEBUG: Stream element:
<taxii_11:Poll_Response xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:xmldsig="http://www.w3.org/2000/09/xmldsig#" collection_name="PhishTank" more="false" result_id="1582588800404:1582675200404" result_part_number="7" in_response_to="2cb6ecfa-7647-4510-b513-17abc4753938" message_id="urn:uuid:81ec21ee-b9c0-4c34-b27d-43205c8ead62"><taxii_11:Exclusive_Begin_Timestamp>2020-02-25T00:00:00.404Z</taxii_11:Exclusive_Begin_Timestamp><taxii_11:Inclusive_End_Timestamp>2020-02-26T00:00:00.404Z</taxii_11:Inclusive_End_Timestamp><taxii_11:Record_Count partial_count="false">508</taxii_11:Record_Count></taxii_11:Poll_Response>
```

```

2021-01-20 12:02:45,751 cabby.dispatcher INFO: Sending Poll_Fulfillment to https://partnerstage.threatconnect.com/api/taxii/poll/
2021-01-20 12:02:45,751 cabby.dispatcher DEBUG: Request:
<taxii_11:Poll_Fulfillment xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="d169300e-5261-4cae-9544-8a8209e06486" collection_name="PhishTank" result_id="1582588800404:1582675200404" **result_part_number="8"**/>

2021-01-20 12:02:45,753 urllib3.connectionpool DEBUG: Starting new HTTPS connection (1): partnerstage.threatconnect.com
^CTraceback (most recent call last):
  File "/usr/bin/taxii-poll", line 11, in <module>
    load_entry_point('cabby==0.1.20', 'console_scripts', 'taxii-poll')()
  File "build/bdist.linux-x86_64/egg/cabby/cli/poll.py", line 160, in poll_content
  File "build/bdist.linux-x86_64/egg/cabby/cli/commons.py", line 171, in run_client
  File "build/bdist.linux-x86_64/egg/cabby/cli/poll.py", line 139, in _runner
  File "build/bdist.linux-x86_64/egg/cabby/client11.py", line 505, in poll
  File "build/bdist.linux-x86_64/egg/cabby/client11.py", line 545, in fulfilment
  File "build/bdist.linux-x86_64/egg/cabby/abstract.py", line 190, in _execute_request
  File "build/bdist.linux-x86_64/egg/cabby/dispatcher.py", line 54, in send_taxii_request
  File "build/bdist.linux-x86_64/egg/cabby/dispatcher.py", line 89, in request_stream
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 766, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len)
KeyboardInterrupt

```
_Manually killed the process as its goes to never ending loop.
Issue is seen every time cabby tries to download multiple blocks._

=============================================================================
**### But with the taxii client it** 

```
[root@vm21centos-1 ~]# poll_client -u https://partnerstage.threatconnect.com/api/taxii/poll --username ******** --pass *********8  --collection PhishTank --begin-timestamp 2020-02-25T00:00:00.404174+00:00  --end-timestamp 2020-02-26T00:00:00.404174+00:00
Request:

Message Type: Poll_Request
Message ID: 543160029855896038
  Collection Name: PhishTank
  Excl. Begin TS Label: 2020-02-25 00:00:00.404174+00:00
  Incl. End TS Label: 2020-02-26 00:00:00.404174+00:00
  === Poll_Parameters ===
    Response type: FULL

Response:

Message Type: Poll_Response
Message ID: urn:uuid:8766717d-5f75-4843-abaa-bbe6a499b36b; In Response To: 543160029855896038
  Collection Name: PhishTank
  More: True
  Result ID: 1582588800404:1582675200404
  Result Part Num: 1
  === Record Count ===
    Record Count: 500
  Excl. Begin TS Label: 2020-02-25T00:00:00.404174+00:00
  Incl. End TS Label: 2020-02-26T00:00:00.404174+00:00
  === Content Block ===
    Content Binding: urn:stix.mitre.org:xml:1.1.1
    Content length: 805885
    (Content not printed for brevity)
    Message: None
    Padding: None

This response has More=True, to request additional parts, use the following command:
  fulfillment_client --collection PhishTank --result-id 1582588800404:1582675200404 --result-part-number 2

File created: PhishTank_STIX111_s2021_01_22T12_35_25_073632.xml
```

```
[root@vm21centos-1 ~]# fulfillment_client -u https://partnerstage.threatconnect.com/api/taxii/poll --username ********* --pass *********  --collection PhishTank --result-id 1582588800404:1582675200404 --result-part-number 2
Request:

Message Type: Poll_Fulfillment
Message ID: 8622465795543714864
  Collection Name: PhishTank
  Result ID: 1582588800404:1582675200404
  Result Part Number: 2

Response:

Message Type: Poll_Response
Message ID: urn:uuid:3cfe6c9b-15e3-43b3-851d-63b12b3a68bd; In Response To: 8622465795543714864
  Collection Name: PhishTank
  More: False
  Result ID: 1582588800404:1582675200404
  Result Part Num: 2
  === Record Count ===
    Record Count: 508
  Excl. Begin TS Label: 2020-02-25T00:00:00.404000+00:00
  Incl. End TS Label: 2020-02-26T00:00:00.404000+00:00
  === Content Block ===
    Content Binding: urn:stix.mitre.org:xml:1.1.1
    Content length: 722
    (Content not printed for brevity)
    Message: None
    Padding: None
```
 **its not asking to download result-part-number 3** 

```
[root@vm21centos-1 ~]# fulfillment_client -u https://partnerstage.threatconnect.com/api/taxii/poll --username ********* --pass *********  --collection PhishTank --result-id 1582588800404:1582675200404 --result-part-number 3
Request:

Message Type: Poll_Fulfillment
Message ID: 842267104647120760
  Collection Name: PhishTank
  Result ID: 1582588800404:1582675200404
  Result Part Number: 3

Response:


Message Type: Poll_Response
Message ID: urn:uuid:41eaec3e-b429-4aca-95f9-dd0d5d8aa5b9; In Response To: 842267104647120760
  Collection Name: PhishTank
  More: False
  Result ID: 1582588800404:1582675200404
  Result Part Num: 3
  === Record Count ===
    Record Count: 508
  Excl. Begin TS Label: 2020-02-25T00:00:00.404000+00:00
  Incl. End TS Label: 2020-02-26T00:00:00.404000+00:00
  === Content Block ===
    Content Binding: urn:stix.mitre.org:xml:1.1.1
    Content length: 722
    (Content not printed for brevity)
    Message: None
    Padding: None
```
But still don't see any error if try to download result-part-number 3...

**Comment by arcsector** [comment]
Please format your comment with code blocks for us to read through your response and request logs, thank you.

**Comment by sriramvonline** [comment]
@arcsector thanks, update the comment to code block... is it readable now ?

**Comment by arcsector** [comment]
Thanks @sriramvonline, much better. This appears to be an error with cabby not respecting the `more` attribute in the poll response or fulfillment response, is that right?

**Comment by sriramvonline** [comment]
@arcsector,  thanks for figuring out. Yes, Looks like we don't honor "more" field.

**Comment by sriramvonline** [comment]
> @traut this appears to be an issue with libtaxii getting information from the fulfillment response... I'm not sure what they would need to tweak to fix this.

@traut any update about the fix ?

**Comment by sriramvonline** [comment]
Can someone provide temp fix or work around

**Comment by avanbrunt-cb** [comment]
@sriramvonline Not sure if you are still looking for a fix but I've created one https://github.com/eclecticiq/cabby/pull/81
